### ISSUE TITLE
Couldn't make boost-build successfully

### ISSUE THREAD

**Issue by zizicici** [imfuxiao/LibrimeKit#2]
Env information:

Cocoapods version: 1.12.1
macOS version: 13.4.0 @ M1 Pro
Xcode version: 14.3(14E222b)

----

When I run `make boost-build`

Then I got an error:
`
cp: path/Hamster/Packages/LibrimeKit/boost-iosx/scripts/Pods/icu4c-iosx/product/frameworks/icudata.xcframework/macos-arm64_arm64/libicudata.a: No such file or directory
`

There are 4 folders under icudata.xcframework: `ios-arm64`, `ios-arm64_x86_64-maccatalyst`, `ios-arm64_x86_64-simulator`, `macos-arm64_x86_64`

**Comment by imfuxiao** [comment]
我用的 x86 的 macos，不能还原您的相关环境。

不过看您的信息，应该是缺失了 icu4c，这个应该是通过 pod 来安装的。

脚本是在 boost-iosx/script/build.sh 中，第 42 ~ 50 行

```sh
############### ICU
if [ ! -d $SCRIPT_DIR/Pods/icu4c-iosx/product ]; then
	pushd $SCRIPT_DIR
    pod repo update
	pod install --verbose
	popd
	mkdir $SCRIPT_DIR/Pods/icu4c-iosx/product/lib
fi
ICU_PATH=$SCRIPT_DIR/Pods/icu4c-iosx/product
############### ICU
```

您检查下是否没有先编译 boost-iosx.

**Comment by hsqStephenZhang** [comment]
@zizicici boost-iosx 的版本没有更新，看最新的版本里面，"macos-arm64_arm64" 已经修改成了 "macos-arm64_x86_64"
