### ISSUE TITLE
请求增加 librime-charcode 插件

### ISSUE THREAD

**Issue by ksqsf** [imfuxiao/LibrimeKit#3]
最近给方案添加了 charset_filter 后，发现在仓上无法正常工作。在本仓库中查看了一下，似乎是因为未增加 [librime-charcode 插件](https://github.com/rime/librime-charcode)，希望可以增加之。谢谢！

**Comment by imfuxiao** [comment]
收到，感谢反馈。

**Comment by imfuxiao** [comment]
增加 charcode 插件后，需要添加 5 个依赖包：boost_local 与 Local 依赖 ICU 框架的4个包，导致包体积从 85 MB升至 152 MB。太大了，考虑是否有必要添加这个插件。

**Comment by ksqsf** [comment]
明白了，感谢您的付出！
